// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export function rust_mem_leaked(): number;
export function add_bool(x: boolean, y: boolean): boolean;
export function add_u8(x: number, y: number): number;
export function add_u16(x: number, y: number): number;
export function add_u32(x: number, y: number): number;
export function add_usize(x: number, y: number): number;
export function add_u64(x: bigint, y: bigint): bigint;
export function add_i8(x: number, y: number): number;
export function add_i16(x: number, y: number): number;
export function add_i32(x: number, y: number): number;
export function add_isize(x: number, y: number): number;
export function add_i64(x: bigint, y: bigint): bigint;
export function add_f32(x: number, y: number): number;
export function add_f64(x: number, y: number): number;
