// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>
#include <tuple>

namespace rust {

uintptr_t rust_mem_leaked();

int32_t empty_tuple(int32_t x, std::tuple<> foo, int32_t y);

int32_t single_element_tuple(std::tuple<int32_t> x, std::tuple<int32_t> y);

float multiply_pairs(std::tuple<float, float> ab, std::tuple<float, float> cd);

int32_t nesting(std::tuple<int32_t, std::tuple<>, std::tuple<int32_t, std::tuple<int32_t>>> x);

} // namespace rust
