// This file was generated by miniffi v0.1.0. Do not edit.

export async function instantiate(bytes, imports) {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiate(bytes, { env });
    _ffi_exports = (await promise).instance.exports;
    return { memory: _ffi_exports.memory };
}

export async function instantiateStreaming(source, imports) {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiateStreaming(source, { env });
    _ffi_exports = (await promise).instance.exports;
    return { memory: _ffi_exports.memory };
}

export function rust_mem_leaked() {
    return _ffi_exports._ffi_fn_rust_mem_leaked();
}

export function get_getter_counter() {
    return _ffi_exports._ffi_fn_get_getter_counter();
}

export function get_adder_counter() {
    return _ffi_exports._ffi_fn_get_adder_counter();
}

export function get_getter() {
    let ret_ptr = _ffi_exports._ffi_fn_get_getter();
    return new _ffi_Rc_Getter(ret_ptr);
}

let _ffi_reg_Rc_Adder = new FinalizationRegistry((ptr) => _ffi_exports._ffi_rs_drop_Rc_Adder(ptr));
let _ffi_reg_Rc_Getter = new FinalizationRegistry((ptr) => _ffi_exports._ffi_rs_drop_Rc_Getter(ptr));

const _ffi_Rc_Adder = class Adder {
    constructor(_) {
        Object.defineProperty(this, "_", { value: _ });
        _ffi_reg_Rc_Adder.register(this, _);
    }

    add(x, y) {
        return _ffi_exports._ffi_Rc_Adder__add(this._, x, y);
    }
};

const _ffi_Rc_Getter = class Getter {
    constructor(_) {
        Object.defineProperty(this, "_", { value: _ });
        _ffi_reg_Rc_Getter.register(this, _);
    }

    get_adder() {
        let ret_ptr = _ffi_exports._ffi_Rc_Getter__get_adder(this._);
        return new _ffi_Rc_Adder(ret_ptr);
    }
};

let _ffi_exports;

const _ffi_imports = {};
