// This file was generated by miniffi v0.1.0. Do not edit.

protocol Bar: AnyObject {
    func get() -> Int32
}

struct Foo {
    var ptr: Bar
}

func rust_mem_leaked() -> UInt {
    return _ffi_fn_rust_mem_leaked()
}

func test(_ x: Int32) -> (Int32, Foo) {
    let multi_ret = _ffi_fn_test(x)
    let ret_0 = multi_ret._0
    let ret_1_ptr_ptr = multi_ret._1
    return (ret_0, Foo(ptr: _ffi_Rc_Bar(ret_1_ptr_ptr)))
}

private class _ffi_Rc_Bar : Bar {
    private var _ffi: UnsafeRawPointer?

    init(_ ptr: UnsafeRawPointer?) {
        _ffi = ptr
    }

    deinit {
        _ffi_rs_drop_Rc_Bar(_ffi)
    }

    func get() -> Int32 {
        return _ffi_Rc_Bar__get(_ffi)
    }
}
