// This file was generated by miniffi v0.1.0. Do not edit.

protocol Imported: AnyObject {
    func run(_ exported: Exported) -> Int32
}

protocol Exported: AnyObject {
    func add(_ x: Int32, _ y: Int32) -> Int32
}

func rust_mem_leaked() -> UInt {
    return _ffi_fn_rust_mem_leaked()
}

func get_counter() -> UInt32 {
    return _ffi_fn_get_counter()
}

func set_imported(_ imported: Imported) -> Int32 {
    return _ffi_fn_set_imported(UnsafeRawPointer(Unmanaged.passRetained(imported as AnyObject).toOpaque()))
}

private class _ffi_Rc_Exported : Exported {
    private var _ffi: UnsafeRawPointer?

    init(_ ptr: UnsafeRawPointer?) {
        _ffi = ptr
    }

    deinit {
        _ffi_rs_drop_Rc_Exported(_ffi)
    }

    func add(_ x: Int32, _ y: Int32) -> Int32 {
        return _ffi_Rc_Exported__add(_ffi, x, y)
    }
}

@_cdecl("_ffi_swift_Imported__run")
func _ffi_swift_Imported__run(_self: UnsafeRawPointer?, exported_ptr: UnsafeRawPointer?) -> Int32 {
    let _self = Unmanaged<AnyObject>.fromOpaque(_self!).takeUnretainedValue() as! Imported
    return _self.run(_ffi_Rc_Exported(exported_ptr))
}

@_cdecl("_ffi_swift_drop")
func _ffi_swift_drop(ptr: UnsafeRawPointer?) {
    _ = Unmanaged<AnyObject>.fromOpaque(ptr!).takeRetainedValue()
}
