// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t _ffi_Rc_Exported__run(const void*, const void* imported_ptr);

uint32_t _ffi_fn_get_counter();

const void* _ffi_fn_get_exported();

uintptr_t _ffi_fn_rust_mem_leaked();

void _ffi_rs_drop_Rc_Exported(const void* ptr);

#ifdef __cplusplus
}
#endif
