// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <memory>
#include <stdint.h>

namespace rust {

struct Adder {
    virtual ~Adder() {}
    virtual int32_t add(int32_t y) = 0;
};

uintptr_t rust_mem_leaked();

int32_t set_adder_rc(std::shared_ptr<Adder> adder);

int32_t set_adder_box(std::unique_ptr<Adder> adder);

} // namespace rust
