// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>
#include <tuple>
#include <memory>

namespace rust {

struct Bar;

struct Bar {
    virtual ~Bar() {}
    virtual int32_t get() = 0;
};

struct Foo {
    std::shared_ptr<Bar> ptr;
};

uintptr_t rust_mem_leaked();

std::tuple<int32_t, Foo> test(int32_t x);

} // namespace rust
