// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t _ffi_Box_Foo__get_enum(const void*);

void _ffi_Box_Foo__set_enum(const void*, int32_t bar_raw);

const void* _ffi_fn_get_foo();

uintptr_t _ffi_fn_rust_mem_leaked();

void _ffi_rs_drop_Box_Foo(const void* ptr);

#ifdef __cplusplus
}
#endif
