// This file was generated by miniffi v0.1.0. Do not edit.

export async function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }> {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiate(bytes, { env });
    _ffi_exports = (await promise).instance.exports as any;
    return { memory: _ffi_exports.memory };
}

export async function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }> {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiateStreaming(source, { env });
    _ffi_exports = (await promise).instance.exports as any;
    return { memory: _ffi_exports.memory };
}

export interface Platform {
    create_window(): Window;
}

export interface Window {
    get_title(): string;
    set_title(title: string): void;
    get_size(): [number, number];
    set_size(width: number, height: number): void;
    set_handler(handler: Handler): void;
    child_window(): Window;
}

export interface Handler {
    on_draw(canvas: Canvas): void;
}

export interface Canvas {
    draw_text_runs(runs: TextRun[]): void;
}

export interface TextRun {
    text: string,
    rect: TextRect,
}

export interface TextRect {
    x: number,
    y: number,
    w: number,
    h: number,
}

export function rust_mem_leaked(): number {
    return _ffi_exports._ffi_fn_rust_mem_leaked();
}

export function create_app(platform: Platform): void {
    _ffi_exports._ffi_fn_create_app(_ffi_handle_alloc(platform));
}

let _ffi_len = 0;
let _ffi_dv: DataView;
let _ffi_new_ReadBuf = (off: number): _ffi_ReadBuf => ({ dv: _ffi_update_dv(), off });
let _ffi_reg_Box_Handler = new FinalizationRegistry((ptr: number) => _ffi_exports._ffi_rs_drop_Box_Handler(ptr));
let _ffi_handles: Map<number, any> = /* @__PURE__ */ new Map;
let _ffi_next_handle = 0;
let _ffi_decoder = /* @__PURE__ */ new TextDecoder;
let _ffi_encoder = /* @__PURE__ */ new TextEncoder;
let _ffi_u8: Uint8Array;

interface _ffi_ReadBuf {
    dv: DataView,
    off: number,
}

function _ffi_update_dv(): DataView {
    let buffer = _ffi_exports.memory.buffer;
    if (!_ffi_dv || _ffi_dv.buffer !== buffer) _ffi_dv = new DataView(buffer);
    return _ffi_dv;
}

const _ffi_Box_Handler = class Handler implements Handler {
    declare readonly _: number;

    constructor(_: number) {
        Object.defineProperty(this, "_", { value: _ });
        _ffi_reg_Box_Handler.register(this, _);
    }

    on_draw(canvas: Canvas): void {
        _ffi_exports._ffi_Box_Handler__on_draw(this._, _ffi_handle_alloc(canvas));
    }
};

function _ffi_handle_alloc(obj: any): number {
    _ffi_handles.set(++_ffi_next_handle, obj);
    return _ffi_next_handle;
}

function _ffi_read_i32(buf: _ffi_ReadBuf): number {
    let val = buf.dv.getInt32(buf.off, true);
    buf.off += 4;
    return val;
}

function _ffi_read_u32(buf: _ffi_ReadBuf): number {
    let val = buf.dv.getUint32(buf.off, true);
    buf.off += 4;
    return val;
}

function _ffi_string_from_rust(ptr: number, len: number, cap: number): string {
    let str = _ffi_decoder.decode(new Uint8Array(_ffi_exports.memory.buffer, ptr, len));
    _ffi_exports._ffi_dealloc(ptr, cap);
    return str;
}

function _ffi_update_u8(): Uint8Array {
    let buffer = _ffi_exports.memory.buffer;
    if (!_ffi_u8 || _ffi_u8.buffer !== buffer) _ffi_u8 = new Uint8Array(buffer);
    return _ffi_u8;
}

function _ffi_string_to_rust(str: string): number {
    let buf = _ffi_encoder.encode(str);
    let ptr = _ffi_exports._ffi_alloc(_ffi_len = buf.length);
    _ffi_update_u8().set(buf, ptr);
    return ptr;
}

function _ffi_vec_TextRun_from_rust(len: number, buf: _ffi_ReadBuf): TextRun[] {
    let items: TextRun[] = [];
    while (items.length < len) {
        items.push({
            text: _ffi_string_from_rust(_ffi_read_i32(buf), _ffi_read_u32(buf), _ffi_read_u32(buf)),
            rect: { x: _ffi_read_i32(buf), y: _ffi_read_i32(buf), w: _ffi_read_i32(buf), h: _ffi_read_i32(buf) }
        });
    }
    return items;
}

let _ffi_exports: {
    memory: WebAssembly.Memory,
    _ffi_Box_Handler__on_draw: (_self: number, canvas_ptr: number) => void,
    _ffi_dealloc: (ptr: number, capacity: number) => void,
    _ffi_fn_create_app: (platform_ptr: number) => void,
    _ffi_fn_rust_mem_leaked: () => number,
    _ffi_rs_drop_Box_Handler: (ptr: number) => void,
    _ffi_alloc: (len: number) => number,
};

const _ffi_imports = {
    _ffi_js_Canvas__draw_text_runs(self: number, buf_ptr: number, buf_cap: number, runs_len: number): void {
        let buf = _ffi_new_ReadBuf(buf_ptr);
        _ffi_handles.get(self).draw_text_runs(_ffi_vec_TextRun_from_rust(runs_len, buf));
        _ffi_exports._ffi_dealloc(buf_ptr, buf_cap);
    },

    _ffi_js_Platform__create_window(self: number): number {
        return _ffi_handle_alloc(_ffi_handles.get(self).create_window());
    },

    _ffi_js_Window__child_window(self: number): number {
        return _ffi_handle_alloc(_ffi_handles.get(self).child_window());
    },

    _ffi_js_Window__get_size(self: number, _ffi_ret_2_i32: number): void {
        let ret = _ffi_handles.get(self).get_size();
        _ffi_update_dv().setInt32(_ffi_ret_2_i32, ret[0], true);
        _ffi_dv.setInt32(_ffi_ret_2_i32 + 4, ret[1], true);
    },

    _ffi_js_Window__get_title(self: number, _ffi_ret_ptr_usize: number): void {
        let ret_ptr = _ffi_string_to_rust(_ffi_handles.get(self).get_title()), ret_len = _ffi_len;
        _ffi_update_dv().setInt32(_ffi_ret_ptr_usize, ret_ptr, true);
        _ffi_dv.setInt32(_ffi_ret_ptr_usize + 4, ret_len, true);
    },

    _ffi_js_Window__set_handler(self: number, handler_ptr: number): void {
        _ffi_handles.get(self).set_handler(new _ffi_Box_Handler(handler_ptr));
    },

    _ffi_js_Window__set_size(self: number, width: number, height: number): void {
        _ffi_handles.get(self).set_size(width, height);
    },

    _ffi_js_Window__set_title(self: number, title_ptr: number, title_len: number, title_cap: number): void {
        _ffi_handles.get(self).set_title(_ffi_string_from_rust(title_ptr, title_len, title_cap));
    },

    _ffi_js_drop(handle: number): void {
        _ffi_handles.delete(handle);
    },
};
