// This file was generated by miniffi v0.1.0. Do not edit.

export async function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }> {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiate(bytes, { env });
    _ffi_exports = (await promise).instance.exports as any;
    return { memory: _ffi_exports.memory };
}

export async function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }> {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiateStreaming(source, { env });
    _ffi_exports = (await promise).instance.exports as any;
    return { memory: _ffi_exports.memory };
}

export interface Getter {
    get_adder(): Adder;
}

export interface Adder {
    add(x: number, y: number): number;
}

export function rust_mem_leaked(): number {
    return _ffi_exports._ffi_fn_rust_mem_leaked();
}

export function get_getter_counter(): number {
    return _ffi_exports._ffi_fn_get_getter_counter();
}

export function get_adder_counter(): number {
    return _ffi_exports._ffi_fn_get_adder_counter();
}

export function get_getter(): Getter {
    let ret_ptr = _ffi_exports._ffi_fn_get_getter();
    return new _ffi_Rc_Getter(ret_ptr);
}

let _ffi_reg_Rc_Adder = new FinalizationRegistry((ptr: number) => _ffi_exports._ffi_rs_drop_Rc_Adder(ptr));
let _ffi_reg_Rc_Getter = new FinalizationRegistry((ptr: number) => _ffi_exports._ffi_rs_drop_Rc_Getter(ptr));

const _ffi_Rc_Adder = class Adder implements Adder {
    declare readonly _: number;

    constructor(_: number) {
        Object.defineProperty(this, "_", { value: _ });
        _ffi_reg_Rc_Adder.register(this, _);
    }

    add(x: number, y: number): number {
        return _ffi_exports._ffi_Rc_Adder__add(this._, x, y);
    }
};

const _ffi_Rc_Getter = class Getter implements Getter {
    declare readonly _: number;

    constructor(_: number) {
        Object.defineProperty(this, "_", { value: _ });
        _ffi_reg_Rc_Getter.register(this, _);
    }

    get_adder(): Adder {
        let ret_ptr = _ffi_exports._ffi_Rc_Getter__get_adder(this._);
        return new _ffi_Rc_Adder(ret_ptr);
    }
};

let _ffi_exports: {
    memory: WebAssembly.Memory,
    _ffi_Rc_Adder__add: (_self: number, x: number, y: number) => number,
    _ffi_Rc_Getter__get_adder: (_self: number) => number,
    _ffi_fn_get_adder_counter: () => number,
    _ffi_fn_get_getter: () => number,
    _ffi_fn_get_getter_counter: () => number,
    _ffi_fn_rust_mem_leaked: () => number,
    _ffi_rs_drop_Rc_Adder: (ptr: number) => void,
    _ffi_rs_drop_Rc_Getter: (ptr: number) => void,
};

const _ffi_imports = {};
