// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

uintptr_t _ffi_fn_rust_mem_leaked();

int32_t _ffi_fn_set_empty_tuple(const void* tuple_in_ptr);

float _ffi_fn_set_multiply_pairs(const void* tuple_in_ptr);

int32_t _ffi_fn_set_single_element_tuple(const void* tuple_in_ptr);

#ifdef __cplusplus
}
#endif
