// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export interface EmptyStruct {
}

export interface SingleElementStruct {
    0: number,
}

export interface PairStruct {
    x: number,
    y: number,
}

export function rust_mem_leaked(): number;
export function empty_struct(): EmptyStruct;
export function single_element_struct(x: number): SingleElementStruct;
export function make_pair(x: number, y: number): PairStruct;
