// This file was generated by miniffi v0.1.0. Do not edit.

export async function instantiate(bytes, imports) {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiate(bytes, { env });
    _ffi_exports = (await promise).instance.exports;
    return { memory: _ffi_exports.memory };
}

export async function instantiateStreaming(source, imports) {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiateStreaming(source, { env });
    _ffi_exports = (await promise).instance.exports;
    return { memory: _ffi_exports.memory };
}

export function rust_mem_leaked() {
    return _ffi_exports._ffi_fn_rust_mem_leaked();
}

export function empty_struct() {
    _ffi_exports._ffi_fn_empty_struct();
    return {};
}

export function single_element_struct(x) {
    let ret_0 = _ffi_exports._ffi_fn_single_element_struct(x);
    return { 0: ret_0 };
}

export function make_pair(x, y) {
    let multi_ret = _ffi_exports._ffi_fn_make_pair(x, y);
    let ret_x = _ffi_update_dv().getFloat32(multi_ret, true);
    let ret_y = _ffi_dv.getFloat32(multi_ret + 4, true);
    return { x: ret_x, y: ret_y };
}

let _ffi_dv;

function _ffi_update_dv() {
    let buffer = _ffi_exports.memory.buffer;
    if (!_ffi_dv || _ffi_dv.buffer !== buffer) _ffi_dv = new DataView(buffer);
    return _ffi_dv;
}

let _ffi_exports;

const _ffi_imports = {};
