// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t _ffi_fn_big_to_i32(int32_t big_raw);

int32_t _ffi_fn_foo_to_i32(int32_t foo_raw);

uintptr_t _ffi_fn_rust_mem_leaked();

#ifdef __cplusplus
}
#endif
