// This file was generated by miniffi v0.1.0. Do not edit.

#[unsafe(no_mangle)]
extern "C" fn _ffi_alloc(len: usize) -> *const u8 {
    Box::into_raw([0 as u8].repeat(len).into_boxed_slice()) as *const u8
}

fn _ffi_buf_from_host(ptr: *const u8, end: *const u8) {
    let len = unsafe { end.byte_offset_from(ptr) } as usize;
    drop(unsafe { Vec::from_raw_parts(ptr as *mut u8, 0, len) });
}

#[allow(non_snake_case)]
fn _ffi_enum_Big_from_swift(val: i32) -> Big {
    match val {
        -2147483648 => Big::Min,
        2147483647 => Big::Max,
        _ => panic!(),
    }
}

#[allow(non_snake_case)]
fn _ffi_enum_Foo_from_swift(val: i32) -> Foo {
    match val {
        0 => Foo::Zero,
        1 => Foo::One,
        100 => Foo::Hundred,
        _ => panic!(),
    }
}

fn _ffi_read<T: Copy>(ptr: &mut *const u8) -> T {
    let val = unsafe { (*ptr as *const T).read_unaligned() };
    *ptr = unsafe { ptr.byte_offset(std::mem::size_of::<T>() as isize) };
    val
}

#[allow(non_snake_case)]
fn _ffi_enum_LongEnum_from_swift(end: &mut *const u8) -> LongEnum {
    match _ffi_read::<i32>(end) {
        0 => LongEnum::Empty,
        1 => LongEnum::ShortTuple(_ffi_read::<i32>(end)),
        2 => LongEnum::ShortStruct { a: _ffi_read::<i32>(end) },
        3 => LongEnum::LongTuple(
            _ffi_read::<i32>(end),
            _ffi_read::<i32>(end),
            _ffi_read::<i32>(end),
            _ffi_read::<i32>(end),
            _ffi_read::<i32>(end),
            _ffi_read::<i32>(end),
            _ffi_read::<i32>(end),
            _ffi_read::<i32>(end)
        ),
        4 => LongEnum::LongStruct {
            a: _ffi_read::<i32>(end),
            b: _ffi_read::<i32>(end),
            c: _ffi_read::<i32>(end),
            d: _ffi_read::<i32>(end),
            e: _ffi_read::<i32>(end),
            f: _ffi_read::<i32>(end)
        },
        _ => panic!(),
    }
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_big_to_i32(big_raw: i32) -> i32 {
    big_to_i32(_ffi_enum_Big_from_swift(big_raw))
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_foo_to_i32(foo_raw: i32) -> i32 {
    foo_to_i32(_ffi_enum_Foo_from_swift(foo_raw))
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_long_in(buf_ptr: *const u8) {
    let mut buf_end = buf_ptr;
    long_in(_ffi_enum_LongEnum_from_swift(&mut buf_end));
    _ffi_buf_from_host(buf_ptr, buf_end);
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_rust_mem_leaked() -> usize {
    rust_mem_leaked()
}
