// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export const enum Foo {
    Zero,
    One,
    Hundred = 100,
}

export const enum Big {
    Min = -2147483648,
    Max = 2147483647,
}

export type LongEnum =
    | { readonly $: "Empty" }
    | { readonly $: "ShortTuple", 0: number }
    | { readonly $: "ShortStruct", a: number }
    | { readonly $: "LongTuple", 0: number, 1: number, 2: number, 3: number, 4: number, 5: number, 6: number, 7: number }
    | { readonly $: "LongStruct", a: number, b: number, c: number, d: number, e: number, f: number }

export function rust_mem_leaked(): number;
export function i32_to_foo(foo: number): Foo;
export function i32_to_big(big: number): Big;
export function long_out(): LongEnum;
