// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t _ffi_Box_Trait__get(const void*);

int32_t _ffi_Rc_Trait__get(const void*);

void* _ffi_alloc(intptr_t len);

void _ffi_dealloc(const void* ptr, uintptr_t capacity);

uintptr_t _ffi_fn_rust_mem_leaked();

typedef struct {
    const void* _0;
    uintptr_t _1;
    uintptr_t _2;
} _ffi_ret_ptr_2_usize;

_ffi_ret_ptr_2_usize _ffi_fn_test(const void* buf_ptr, uintptr_t vec_len);

void _ffi_rs_drop_Box_Trait(const void* ptr);

void _ffi_rs_drop_Rc_Trait(const void* ptr);

#ifdef __cplusplus
}
#endif
