// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export interface Test {
    get_string(): string;
    set_string(x: string): void;
    set_str(x: string): void;
}

export function rust_mem_leaked(): number;
export function get_test(): Test;
export function set_test(test: Test): string;
