// This file was generated by miniffi v0.1.0. Do not edit.

export async function instantiate(bytes, imports) {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiate(bytes, { env });
    _ffi_exports = (await promise).instance.exports;
    return { memory: _ffi_exports.memory };
}

export async function instantiateStreaming(source, imports) {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiateStreaming(source, { env });
    _ffi_exports = (await promise).instance.exports;
    return { memory: _ffi_exports.memory };
}

export function rust_mem_leaked() {
    return _ffi_exports._ffi_fn_rust_mem_leaked();
}

export function get_test() {
    let ret_ptr = _ffi_exports._ffi_fn_get_test();
    return new _ffi_Rc_Test(ret_ptr);
}

export function set_test(test) {
    let multi_ret = _ffi_exports._ffi_fn_set_test(_ffi_handle_alloc(test));
    let ret_ptr = _ffi_update_dv().getInt32(multi_ret, true);
    let ret_len = _ffi_dv.getUint32(multi_ret + 4, true);
    let ret_cap = _ffi_dv.getUint32(multi_ret + 8, true);
    return _ffi_string_from_rust(ret_ptr, ret_len, ret_cap);
}

let _ffi_len = 0;
let _ffi_reg_Rc_Test = new FinalizationRegistry((ptr) => _ffi_exports._ffi_rs_drop_Rc_Test(ptr));
let _ffi_handles = /* @__PURE__ */ new Map;
let _ffi_next_handle = 0;
let _ffi_decoder = /* @__PURE__ */ new TextDecoder;
let _ffi_encoder = /* @__PURE__ */ new TextEncoder;
let _ffi_u8;
let _ffi_dv;

const _ffi_Rc_Test = class Test {
    constructor(_) {
        Object.defineProperty(this, "_", { value: _ });
        _ffi_reg_Rc_Test.register(this, _);
    }

    get_string() {
        let multi_ret = _ffi_exports._ffi_Rc_Test__get_string(this._);
        let ret_ptr = _ffi_update_dv().getInt32(multi_ret, true);
        let ret_len = _ffi_dv.getUint32(multi_ret + 4, true);
        let ret_cap = _ffi_dv.getUint32(multi_ret + 8, true);
        return _ffi_string_from_rust(ret_ptr, ret_len, ret_cap);
    }

    set_string(x) {
        let x_ptr = _ffi_string_to_rust(x), x_len = _ffi_len;
        _ffi_exports._ffi_Rc_Test__set_string(this._, x_ptr, x_len);
    }

    set_str(x) {
        let x_ptr = _ffi_string_to_rust(x), x_len = _ffi_len;
        _ffi_exports._ffi_Rc_Test__set_str(this._, x_ptr, x_len);
    }
};

function _ffi_handle_alloc(obj) {
    _ffi_handles.set(++_ffi_next_handle, obj);
    return _ffi_next_handle;
}

function _ffi_string_from_rust(ptr, len, cap) {
    let str = _ffi_decoder.decode(new Uint8Array(_ffi_exports.memory.buffer, ptr, len));
    _ffi_exports._ffi_dealloc(ptr, cap);
    return str;
}

function _ffi_update_u8() {
    let buffer = _ffi_exports.memory.buffer;
    if (!_ffi_u8 || _ffi_u8.buffer !== buffer) _ffi_u8 = new Uint8Array(buffer);
    return _ffi_u8;
}

function _ffi_string_to_rust(str) {
    let buf = _ffi_encoder.encode(str);
    let ptr = _ffi_exports._ffi_alloc(_ffi_len = buf.length);
    _ffi_update_u8().set(buf, ptr);
    return ptr;
}

function _ffi_update_dv() {
    let buffer = _ffi_exports.memory.buffer;
    if (!_ffi_dv || _ffi_dv.buffer !== buffer) _ffi_dv = new DataView(buffer);
    return _ffi_dv;
}

let _ffi_exports;

const _ffi_imports = {
    _ffi_js_Test__get_string(self, _ffi_ret_ptr_usize) {
        let ret_ptr = _ffi_string_to_rust(_ffi_handles.get(self).get_string()), ret_len = _ffi_len;
        _ffi_update_dv().setInt32(_ffi_ret_ptr_usize, ret_ptr, true);
        _ffi_dv.setInt32(_ffi_ret_ptr_usize + 4, ret_len, true);
    },

    _ffi_js_Test__set_str(self, x_ptr, x_len, x_cap) {
        _ffi_handles.get(self).set_str(_ffi_string_from_rust(x_ptr, x_len, x_cap));
    },

    _ffi_js_Test__set_string(self, x_ptr, x_len, x_cap) {
        _ffi_handles.get(self).set_string(_ffi_string_from_rust(x_ptr, x_len, x_cap));
    },

    _ffi_js_drop(handle) {
        _ffi_handles.delete(handle);
    },
};
