// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>
#include <string>
#include <vector>

namespace rust {

uintptr_t rust_mem_leaked();

uint8_t sum_u8(std::vector<uint8_t> values);

uint16_t sum_u16(std::vector<uint16_t> values);

uint32_t sum_u32(std::vector<uint32_t> values);

uintptr_t sum_usize(std::vector<uintptr_t> values);

uint64_t sum_u64(std::vector<uint64_t> values);

int8_t sum_i8(std::vector<int8_t> values);

int16_t sum_i16(std::vector<int16_t> values);

int32_t sum_i32(std::vector<int32_t> values);

intptr_t sum_isize(std::vector<intptr_t> values);

int64_t sum_i64(std::vector<int64_t> values);

float sum_f32(std::vector<float> values);

double sum_f64(std::vector<double> values);

std::string check_nested(std::vector<std::vector<int32_t>> values);

} // namespace rust
