// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export interface Platform {
    create_window(): Window;
}

export interface Window {
    get_title(): string;
    set_title(title: string): void;
    get_size(): [number, number];
    set_size(width: number, height: number): void;
    set_handler(handler: Handler): void;
    child_window(): Window;
}

export interface Handler {
    on_draw(canvas: Canvas): void;
}

export interface Canvas {
    draw_text_runs(runs: TextRun[]): void;
}

export interface TextRun {
    text: string,
    rect: TextRect,
}

export interface TextRect {
    x: number,
    y: number,
    w: number,
    h: number,
}

export function rust_mem_leaked(): number;
export function create_app(platform: Platform): void;
