// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export interface Foo {
    set_enum(bar: Bar): void;
    get_enum(): Bar;
}

export const enum Bar {
    A,
    B,
    C,
}

export function rust_mem_leaked(): number;
export function get_foo(): Foo;
