// This file was generated by miniffi v0.1.0. Do not edit.

export async function instantiate(bytes, imports) {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiate(bytes, { env });
    _ffi_exports = (await promise).instance.exports;
    return { memory: _ffi_exports.memory };
}

export async function instantiateStreaming(source, imports) {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiateStreaming(source, { env });
    _ffi_exports = (await promise).instance.exports;
    return { memory: _ffi_exports.memory };
}

export const Bar = {
    A: 0,
    B: 1,
    C: 2,
};

export function rust_mem_leaked() {
    return _ffi_exports._ffi_fn_rust_mem_leaked();
}

export function get_foo() {
    let ret_ptr = _ffi_exports._ffi_fn_get_foo();
    return new _ffi_Box_Foo(ret_ptr);
}

let _ffi_reg_Box_Foo = new FinalizationRegistry((ptr) => _ffi_exports._ffi_rs_drop_Box_Foo(ptr));

const _ffi_Box_Foo = class Foo {
    constructor(_) {
        Object.defineProperty(this, "_", { value: _ });
        _ffi_reg_Box_Foo.register(this, _);
    }

    set_enum(bar) {
        _ffi_exports._ffi_Box_Foo__set_enum(this._, bar);
    }

    get_enum() {
        return _ffi_exports._ffi_Box_Foo__get_enum(this._);
    }
};

let _ffi_exports;

const _ffi_imports = {};
