// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export interface Getter {
    get_adder(): Adder;
}

export interface Adder {
    add(x: number, y: number): number;
}

export function rust_mem_leaked(): number;
export function set_getter(getter: Getter): number;
