// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export function rust_mem_leaked(): number;
export function reset(): void;
export function get_string_len(): number;
export function get_string(): string;
export function set_string(x: string): void;
export function set_str(x: string): void;
