// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export interface Trait {
    get(): number;
}

export interface Example {
    box_ptr: Trait,
    rc_ptr: Trait,
    text: string,
    vec_box: Trait[],
    vec_rc: Trait[],
}

export function rust_mem_leaked(): number;
export function test(vec: Example[]): Example[];
