// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export type NestedBox =
    | { readonly $: "Foo" }
    | { readonly $: "Bar", 0: NestedBox }

export type NestedVec =
    | { readonly $: "Foo" }
    | { readonly $: "Bar", 0: NestedVec[] }

export type NestedOption =
    | { readonly $: "Foo" }
    | { readonly $: "Bar", 0: NestedOption | null }

export type NestedTuple =
    | { readonly $: "Foo" }
    | { readonly $: "Bar", 0: [number, NestedTuple] }

export type NestedStruct =
    | { readonly $: "Foo" }
    | { readonly $: "Bar", 0: [number, InnerStruct] }

export type NestedEnum =
    | { readonly $: "Foo" }
    | { readonly $: "Bar", 0: [number, InnerEnum] }

export type InnerEnum =
    | { readonly $: "Foo", 0: NestedEnum }

export interface InnerStruct {
    x: NestedStruct,
}

export function rust_mem_leaked(): number;
