// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void _ffi_dealloc(const void* ptr, uintptr_t capacity);

typedef struct {
    int32_t _0;
    const void* _1;
    uintptr_t _2;
    uintptr_t _3;
    uintptr_t _4;
    uintptr_t _5;
} _ffi_ret_i32_ptr_4_usize;

_ffi_ret_i32_ptr_4_usize _ffi_fn_check_combo1();

_ffi_ret_i32_ptr_4_usize _ffi_fn_check_combo2();

uintptr_t _ffi_fn_rust_mem_leaked();

#ifdef __cplusplus
}
#endif
