// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void _ffi_dealloc(const void* ptr, uintptr_t capacity);

typedef struct {
    const void* _0;
    uintptr_t _1;
    uintptr_t _2;
} _ffi_ret_ptr_2_usize;

_ffi_ret_ptr_2_usize _ffi_fn_get_tests();

uintptr_t _ffi_fn_rust_mem_leaked();

#ifdef __cplusplus
}
#endif
