// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t _ffi_Rc_Exported__add(const void*, int32_t x, int32_t y);

uint32_t _ffi_fn_get_counter();

uintptr_t _ffi_fn_rust_mem_leaked();

int32_t _ffi_fn_set_imported(const void* imported_ptr);

void _ffi_rs_drop_Rc_Exported(const void* ptr);

#ifdef __cplusplus
}
#endif
