// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    float _0;
    _Bool _1;
} _ffi_ret_f32_bool;

_ffi_ret_f32_bool _ffi_fn_return_pair(float x, _Bool y);

uintptr_t _ffi_fn_rust_mem_leaked();

int32_t _ffi_fn_single_element_tuple(int32_t x);

#ifdef __cplusplus
}
#endif
