// This file was generated by miniffi v0.1.0. Do not edit.

func rust_mem_leaked() -> UInt {
    return _ffi_fn_rust_mem_leaked()
}

func single_element_tuple(_ x: Int32) -> Int32 {
    let ret_0 = _ffi_fn_single_element_tuple(x)
    return ret_0
}

func return_pair(_ x: Float32, _ y: Bool) -> (Float32, Bool) {
    let multi_ret = _ffi_fn_return_pair(x, y)
    let ret_0 = multi_ret._0
    let ret_1 = multi_ret._1
    return (ret_0, ret_1)
}
