// This file was generated by miniffi v0.1.0. Do not edit.

export async function instantiate(bytes, imports) {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiate(bytes, { env });
    _ffi_exports = (await promise).instance.exports;
    return { memory: _ffi_exports.memory };
}

export async function instantiateStreaming(source, imports) {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiateStreaming(source, { env });
    _ffi_exports = (await promise).instance.exports;
    return { memory: _ffi_exports.memory };
}

export function rust_mem_leaked() {
    return _ffi_exports._ffi_fn_rust_mem_leaked();
}

export function reset() {
    _ffi_exports._ffi_fn_reset();
}

export function get_string_len() {
    return _ffi_exports._ffi_fn_get_string_len();
}

export function get_string() {
    let multi_ret = _ffi_exports._ffi_fn_get_string();
    let ret_ptr = _ffi_update_dv().getInt32(multi_ret, true);
    let ret_len = _ffi_dv.getUint32(multi_ret + 4, true);
    let ret_cap = _ffi_dv.getUint32(multi_ret + 8, true);
    return _ffi_string_from_rust(ret_ptr, ret_len, ret_cap);
}

export function set_string(x) {
    let x_ptr = _ffi_string_to_rust(x), x_len = _ffi_len;
    _ffi_exports._ffi_fn_set_string(x_ptr, x_len);
}

export function set_str(x) {
    let x_ptr = _ffi_string_to_rust(x), x_len = _ffi_len;
    _ffi_exports._ffi_fn_set_str(x_ptr, x_len);
}

let _ffi_len = 0;
let _ffi_decoder = /* @__PURE__ */ new TextDecoder;
let _ffi_encoder = /* @__PURE__ */ new TextEncoder;
let _ffi_u8;
let _ffi_dv;

function _ffi_string_from_rust(ptr, len, cap) {
    let str = _ffi_decoder.decode(new Uint8Array(_ffi_exports.memory.buffer, ptr, len));
    _ffi_exports._ffi_dealloc(ptr, cap);
    return str;
}

function _ffi_update_u8() {
    let buffer = _ffi_exports.memory.buffer;
    if (!_ffi_u8 || _ffi_u8.buffer !== buffer) _ffi_u8 = new Uint8Array(buffer);
    return _ffi_u8;
}

function _ffi_string_to_rust(str) {
    let buf = _ffi_encoder.encode(str);
    let ptr = _ffi_exports._ffi_alloc(_ffi_len = buf.length);
    _ffi_update_u8().set(buf, ptr);
    return ptr;
}

function _ffi_update_dv() {
    let buffer = _ffi_exports.memory.buffer;
    if (!_ffi_dv || _ffi_dv.buffer !== buffer) _ffi_dv = new DataView(buffer);
    return _ffi_dv;
}

let _ffi_exports;

const _ffi_imports = {};
