// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t _ffi_Rc_Bar__get(const void*);

uintptr_t _ffi_fn_rust_mem_leaked();

typedef struct {
    int32_t _0;
    const void* _1;
} _ffi_ret_i32_ptr;

_ffi_ret_i32_ptr _ffi_fn_test(int32_t x);

void _ffi_rs_drop_Rc_Bar(const void* ptr);

#ifdef __cplusplus
}
#endif
