// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <memory>
#include <stdint.h>

namespace rust {

struct Exported;

struct Exported {
    virtual ~Exported() {}
    virtual int32_t add(int32_t x, int32_t y) = 0;
};

struct Imported {
    virtual ~Imported() {}
    virtual int32_t run(std::shared_ptr<Exported> exported) = 0;
};

uintptr_t rust_mem_leaked();

uint32_t get_counter();

int32_t set_imported(std::shared_ptr<Imported> imported);

} // namespace rust
