// This file was generated by miniffi v0.1.0. Do not edit.

struct EmptyStruct : Equatable {
}

struct SingleElementStruct : Equatable {
    var _0: Int32
}

struct PairStruct : Equatable {
    var x: Float32
    var y: Float32
}

func rust_mem_leaked() -> UInt {
    return _ffi_fn_rust_mem_leaked()
}

func empty_struct() -> EmptyStruct {
    _ffi_fn_empty_struct()
    return EmptyStruct()
}

func single_element_struct(_ x: Int32) -> SingleElementStruct {
    let ret_0 = _ffi_fn_single_element_struct(x)
    return SingleElementStruct(_0: ret_0)
}

func make_pair(_ x: Float32, _ y: Float32) -> PairStruct {
    let multi_ret = _ffi_fn_make_pair(x, y)
    let ret_x = multi_ret._0
    let ret_y = multi_ret._1
    return PairStruct(x: ret_x, y: ret_y)
}
