// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void _ffi_fn_empty_struct();

typedef struct {
    float _0;
    float _1;
} _ffi_ret_2_f32;

_ffi_ret_2_f32 _ffi_fn_make_pair(float x, float y);

uintptr_t _ffi_fn_rust_mem_leaked();

int32_t _ffi_fn_single_element_struct(int32_t x);

#ifdef __cplusplus
}
#endif
