// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export function rust_mem_leaked(): number;
export function empty_tuple(x: number, foo: undefined, y: number): number;
export function single_element_tuple(x: [number], y: [number]): number;
export function multiply_pairs(ab: [number, number], cd: [number, number]): number;
export function nesting(x: [number, undefined, [number, [number]]]): number;
