// This file was generated by miniffi v0.1.0. Do not edit.

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_rust_mem_leaked() -> usize {
    rust_mem_leaked()
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_alignas(alignas2: i32) -> i32 {
    test_alignas(alignas2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_alignof(alignof2: i32) -> i32 {
    test_alignof(alignof2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_and(and2: i32) -> i32 {
    test_and(and2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_and_eq(and_eq2: i32) -> i32 {
    test_and_eq(and_eq2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_asm(asm2: i32) -> i32 {
    test_asm(asm2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_associatedtype(associatedtype: i32) -> i32 {
    test_associatedtype(associatedtype)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_associativity(associativity: i32) -> i32 {
    test_associativity(associativity)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_atomic_cancel(atomic_cancel2: i32) -> i32 {
    test_atomic_cancel(atomic_cancel2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_atomic_commit(atomic_commit2: i32) -> i32 {
    test_atomic_commit(atomic_commit2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_atomic_noexcept(atomic_noexcept2: i32) -> i32 {
    test_atomic_noexcept(atomic_noexcept2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_auto(auto2: i32) -> i32 {
    test_auto(auto2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_bitand(bitand2: i32) -> i32 {
    test_bitand(bitand2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_bitor(bitor2: i32) -> i32 {
    test_bitor(bitor2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_bool(bool2: i32) -> i32 {
    test_bool(bool2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_boolean(boolean: i32) -> i32 {
    test_boolean(boolean)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_borrowing(borrowing: i32) -> i32 {
    test_borrowing(borrowing)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_byte(byte: i32) -> i32 {
    test_byte(byte)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_case(case2: i32) -> i32 {
    test_case(case2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_catch(catch2: i32) -> i32 {
    test_catch(catch2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_char(char2: i32) -> i32 {
    test_char(char2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_char16_t(char16_t2: i32) -> i32 {
    test_char16_t(char16_t2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_char32_t(char32_t2: i32) -> i32 {
    test_char32_t(char32_t2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_char8_t(char8_t2: i32) -> i32 {
    test_char8_t(char8_t2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_class(class2: i32) -> i32 {
    test_class(class2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_co_await(co_await2: i32) -> i32 {
    test_co_await(co_await2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_co_return(co_return2: i32) -> i32 {
    test_co_return(co_return2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_co_yield(co_yield2: i32) -> i32 {
    test_co_yield(co_yield2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_compl(compl2: i32) -> i32 {
    test_compl(compl2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_concept(concept2: i32) -> i32 {
    test_concept(concept2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_const_cast(const_cast2: i32) -> i32 {
    test_const_cast(const_cast2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_consteval(consteval2: i32) -> i32 {
    test_consteval(consteval2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_constexpr(constexpr2: i32) -> i32 {
    test_constexpr(constexpr2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_constinit(constinit2: i32) -> i32 {
    test_constinit(constinit2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_consuming(consuming: i32) -> i32 {
    test_consuming(consuming)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_contract_assert(contract_assert2: i32) -> i32 {
    test_contract_assert(contract_assert2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_convenience(convenience: i32) -> i32 {
    test_convenience(convenience)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_debugger(debugger: i32) -> i32 {
    test_debugger(debugger)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_decltype(decltype2: i32) -> i32 {
    test_decltype(decltype2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_default(default2: i32) -> i32 {
    test_default(default2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_defer(defer: i32) -> i32 {
    test_defer(defer)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_deinit(deinit: i32) -> i32 {
    test_deinit(deinit)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_delete(delete2: i32) -> i32 {
    test_delete(delete2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_double(double2: i32) -> i32 {
    test_double(double2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_dynamic(dynamic: i32) -> i32 {
    test_dynamic(dynamic)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_dynamic_cast(dynamic_cast2: i32) -> i32 {
    test_dynamic_cast(dynamic_cast2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_explicit(explicit2: i32) -> i32 {
    test_explicit(explicit2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_export(export2: i32) -> i32 {
    test_export(export2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_extends(extends: i32) -> i32 {
    test_extends(extends)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_extension(extension: i32) -> i32 {
    test_extension(extension)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_fallthrough(fallthrough: i32) -> i32 {
    test_fallthrough(fallthrough)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_fileprivate(fileprivate: i32) -> i32 {
    test_fileprivate(fileprivate)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_finally(finally: i32) -> i32 {
    test_finally(finally)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_float(float2: i32) -> i32 {
    test_float(float2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_friend(friend2: i32) -> i32 {
    test_friend(friend2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_func(func: i32) -> i32 {
    test_func(func)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_function(function: i32) -> i32 {
    test_function(function)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_get(get: i32) -> i32 {
    test_get(get)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_goto(goto2: i32) -> i32 {
    test_goto(goto2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_guard(guard: i32) -> i32 {
    test_guard(guard)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_implements(implements: i32) -> i32 {
    test_implements(implements)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_import(import: i32) -> i32 {
    test_import(import)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_indirect(indirect: i32) -> i32 {
    test_indirect(indirect)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_infix(infix: i32) -> i32 {
    test_infix(infix)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_init(init: i32) -> i32 {
    test_init(init)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_inline(inline2: i32) -> i32 {
    test_inline(inline2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_inout(inout: i32) -> i32 {
    test_inout(inout)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_instanceof(instanceof: i32) -> i32 {
    test_instanceof(instanceof)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_int(int2: i32) -> i32 {
    test_int(int2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_interface(interface: i32) -> i32 {
    test_interface(interface)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_internal(internal: i32) -> i32 {
    test_internal(internal)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_is(is: i32) -> i32 {
    test_is(is)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_lazy(lazy: i32) -> i32 {
    test_lazy(lazy)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_left(left: i32) -> i32 {
    test_left(left)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_long(long2: i32) -> i32 {
    test_long(long2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_mutable(mutable2: i32) -> i32 {
    test_mutable(mutable2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_mutating(mutating: i32) -> i32 {
    test_mutating(mutating)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_namespace(namespace2: i32) -> i32 {
    test_namespace(namespace2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_native(native: i32) -> i32 {
    test_native(native)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_new(new2: i32) -> i32 {
    test_new(new2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_nil(nil: i32) -> i32 {
    test_nil(nil)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_noexcept(noexcept2: i32) -> i32 {
    test_noexcept(noexcept2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_none(none: i32) -> i32 {
    test_none(none)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_nonisolated(nonisolated: i32) -> i32 {
    test_nonisolated(nonisolated)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_nonmutating(nonmutating: i32) -> i32 {
    test_nonmutating(nonmutating)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_not(not2: i32) -> i32 {
    test_not(not2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_not_eq(not_eq2: i32) -> i32 {
    test_not_eq(not_eq2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_null(null: i32) -> i32 {
    test_null(null)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_nullptr(nullptr2: i32) -> i32 {
    test_nullptr(nullptr2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_open(open: i32) -> i32 {
    test_open(open)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_operator(operator2: i32) -> i32 {
    test_operator(operator2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_optional(optional: i32) -> i32 {
    test_optional(optional)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_or(or2: i32) -> i32 {
    test_or(or2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_or_eq(or_eq2: i32) -> i32 {
    test_or_eq(or_eq2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_package(package: i32) -> i32 {
    test_package(package)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_postfix(postfix: i32) -> i32 {
    test_postfix(postfix)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_precedence(precedence: i32) -> i32 {
    test_precedence(precedence)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_precedencegroup(precedencegroup: i32) -> i32 {
    test_precedencegroup(precedencegroup)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_prefix(prefix: i32) -> i32 {
    test_prefix(prefix)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_private(private2: i32) -> i32 {
    test_private(private2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_protected(protected2: i32) -> i32 {
    test_protected(protected2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_protocol(protocol: i32) -> i32 {
    test_protocol(protocol)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_public(public2: i32) -> i32 {
    test_public(public2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_reflexpr(reflexpr2: i32) -> i32 {
    test_reflexpr(reflexpr2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_register(register2: i32) -> i32 {
    test_register(register2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_reinterpret_cast(reinterpret_cast2: i32) -> i32 {
    test_reinterpret_cast(reinterpret_cast2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_repeat(repeat: i32) -> i32 {
    test_repeat(repeat)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_required(required: i32) -> i32 {
    test_required(required)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_requires(requires2: i32) -> i32 {
    test_requires(requires2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_rethrows(rethrows: i32) -> i32 {
    test_rethrows(rethrows)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_right(right: i32) -> i32 {
    test_right(right)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_set(set: i32) -> i32 {
    test_set(set)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_short(short2: i32) -> i32 {
    test_short(short2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_signed(signed2: i32) -> i32 {
    test_signed(signed2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_sizeof(sizeof2: i32) -> i32 {
    test_sizeof(sizeof2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_some(some: i32) -> i32 {
    test_some(some)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_static_assert(static_assert2: i32) -> i32 {
    test_static_assert(static_assert2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_static_cast(static_cast2: i32) -> i32 {
    test_static_cast(static_cast2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_subscript(subscript: i32) -> i32 {
    test_subscript(subscript)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_switch(switch2: i32) -> i32 {
    test_switch(switch2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_synchronized(synchronized2: i32) -> i32 {
    test_synchronized(synchronized2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_template(template2: i32) -> i32 {
    test_template(template2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_this(this2: i32) -> i32 {
    test_this(this2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_thread_local(thread_local2: i32) -> i32 {
    test_thread_local(thread_local2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_throw(throw2: i32) -> i32 {
    test_throw(throw2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_throws(throws: i32) -> i32 {
    test_throws(throws)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_transient(transient: i32) -> i32 {
    test_transient(transient)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_typealias(typealias: i32) -> i32 {
    test_typealias(typealias)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_typedef(typedef2: i32) -> i32 {
    test_typedef(typedef2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_typeid(typeid2: i32) -> i32 {
    test_typeid(typeid2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_typename(typename2: i32) -> i32 {
    test_typename(typename2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_undefined(undefined: i32) -> i32 {
    test_undefined(undefined)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_union(union2: i32) -> i32 {
    test_union(union2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_unowned(unowned: i32) -> i32 {
    test_unowned(unowned)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_unsigned(unsigned2: i32) -> i32 {
    test_unsigned(unsigned2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_using(using2: i32) -> i32 {
    test_using(using2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_var(var: i32) -> i32 {
    test_var(var)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_void(void2: i32) -> i32 {
    test_void(void2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_volatile(volatile2: i32) -> i32 {
    test_volatile(volatile2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_wchar_t(wchar_t2: i32) -> i32 {
    test_wchar_t(wchar_t2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_weak(weak: i32) -> i32 {
    test_weak(weak)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_with(with: i32) -> i32 {
    test_with(with)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_xor(xor2: i32) -> i32 {
    test_xor(xor2)
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_test_xor_eq(xor_eq2: i32) -> i32 {
    test_xor_eq(xor_eq2)
}
