// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void* _ffi_alloc(intptr_t len);

void _ffi_dealloc(const void* ptr, uintptr_t capacity);

typedef struct {
    const void* _0;
    uintptr_t _1;
} _ffi_ret_ptr_usize;

_ffi_ret_ptr_usize _ffi_fn_box_opt(const void* buf_ptr);

_ffi_ret_ptr_usize _ffi_fn_box_opt_box(const void* buf_ptr);

_ffi_ret_ptr_usize _ffi_fn_box_tup_0(const void* buf_ptr);

_ffi_ret_ptr_usize _ffi_fn_box_tup_1(const void* buf_ptr);

_ffi_ret_ptr_usize _ffi_fn_box_tup_2(const void* buf_ptr);

_ffi_ret_ptr_usize _ffi_fn_box_vec(const void* buf_ptr);

_ffi_ret_ptr_usize _ffi_fn_box_vec_box(const void* buf_ptr);

void _ffi_fn_empty_struct();

void _ffi_fn_empty_tuple();

_ffi_ret_ptr_usize _ffi_fn_enum_box_tup(const void* buf_ptr);

_ffi_ret_ptr_usize _ffi_fn_enum_opt_tup(const void* buf_ptr);

_ffi_ret_ptr_usize _ffi_fn_enum_vec_tup(const void* buf_ptr);

typedef struct {
    const void* _0;
    uintptr_t _1;
    _Bool _2;
} _ffi_ret_ptr_usize_bool;

_ffi_ret_ptr_usize_bool _ffi_fn_opt_box(const void* buf_ptr, _Bool has_x_0);

_ffi_ret_ptr_usize_bool _ffi_fn_opt_box_opt(const void* buf_ptr, _Bool has_x_0);

_ffi_ret_ptr_usize_bool _ffi_fn_opt_tup_0(const void* buf_ptr, _Bool has_x_0);

_ffi_ret_ptr_usize_bool _ffi_fn_opt_tup_1(const void* buf_ptr, _Bool has_x_0);

_ffi_ret_ptr_usize_bool _ffi_fn_opt_tup_2(const void* buf_ptr, _Bool has_x_0);

uintptr_t _ffi_fn_rust_mem_leaked();

_ffi_ret_ptr_usize _ffi_fn_tup_box(const void* buf_ptr);

typedef struct {
    const void* _0;
    uintptr_t _1;
    uintptr_t _2;
} _ffi_ret_ptr_2_usize;

_ffi_ret_ptr_2_usize _ffi_fn_vec_box(const void* buf_ptr, uintptr_t x_0_len);

_ffi_ret_ptr_2_usize _ffi_fn_vec_box_vec(const void* buf_ptr, uintptr_t x_0_len);

_ffi_ret_ptr_2_usize _ffi_fn_vec_tup_0(const void* buf_ptr, uintptr_t x_0_len);

_ffi_ret_ptr_2_usize _ffi_fn_vec_tup_1(const void* buf_ptr, uintptr_t x_0_len);

_ffi_ret_ptr_2_usize _ffi_fn_vec_tup_2(const void* buf_ptr, uintptr_t x_0_len);

#ifdef __cplusplus
}
#endif
