// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <memory>
#include <stdint.h>

namespace rust {

enum struct Bar : int32_t {
    A = 0,
    B = 1,
    C = 2,
};

struct Foo {
    virtual ~Foo() {}
    virtual void set_enum(Bar bar) = 0;
    virtual Bar get_enum() = 0;
};

uintptr_t rust_mem_leaked();

std::unique_ptr<Foo> get_foo();

} // namespace rust
