// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

namespace rust {

struct EmptyStruct {
};

struct PairStruct {
    float x = 0.0f;
    float y = 0.0f;
};

struct SingleElementStruct {
    int32_t _0 = 0;
};

uintptr_t rust_mem_leaked();

int32_t empty_tuple(int32_t x, EmptyStruct foo, int32_t y);

int32_t single_element_tuple(SingleElementStruct x, SingleElementStruct y);

float multiply_pairs(PairStruct ab, PairStruct cd);

} // namespace rust
