// This file was generated by miniffi v0.1.0. Do not edit.

#include "ffi.h"

extern "C" {

int32_t _ffi_fn_empty_tuple(int32_t x, int32_t y);
float _ffi_fn_multiply_pairs(float ab_x, float ab_y, float cd_x, float cd_y);
uintptr_t _ffi_fn_rust_mem_leaked();
int32_t _ffi_fn_single_element_tuple(int32_t x_0, int32_t y_0);

} // extern "C"

int32_t rust::empty_tuple(int32_t x, rust::EmptyStruct foo, int32_t y) {
    (void)foo;
    return _ffi_fn_empty_tuple(x, y);
}

float rust::multiply_pairs(rust::PairStruct ab, rust::PairStruct cd) {
    return _ffi_fn_multiply_pairs(ab.x, ab.y, cd.x, cd.y);
}

uintptr_t rust::rust_mem_leaked() {
    return _ffi_fn_rust_mem_leaked();
}

int32_t rust::single_element_tuple(rust::SingleElementStruct x, rust::SingleElementStruct y) {
    return _ffi_fn_single_element_tuple(x._0, y._0);
}
