// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export interface StructIn {
    empty_struct(x: number, foo: EmptyStruct, y: number): number;
    single_element_struct(x: SingleElementStruct, y: SingleElementStruct): number;
    multiply_pairs(ab: PairStruct, cd: PairStruct): number;
}

export interface EmptyStruct {
}

export interface SingleElementStruct {
    0: number,
}

export interface PairStruct {
    x: number,
    y: number,
}

export function rust_mem_leaked(): number;
export function set_empty_struct(struct_in: StructIn): number;
export function set_single_element_struct(struct_in: StructIn): number;
export function set_multiply_pairs(struct_in: StructIn): number;
