// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export interface Foo {
    x: [Bar, Bar[]],
    y: [undefined, [number], [number, boolean]][],
}

export interface Bar {
    x: number,
    y: Foo[],
}

export function rust_mem_leaked(): number;
export function check_combo(foo: Foo): string;
