// This file was generated by miniffi v0.1.0. Do not edit.

protocol FirstTrait: AnyObject {
    func second() -> SecondTrait
}

protocol SecondTrait: AnyObject {
    func first() -> FirstTrait
}

enum EarlyInsideEnum {
    case Value(Bool)
}

enum LaterOutsideEnum {
    case Value(EarlyInsideEnum)
}

enum EarlyOutsideEnum {
    case Value(LaterInsideEnum)
}

enum LaterInsideEnum {
    case Value(Bool)
}

enum FirstEnum {
    case Second([SecondEnum])
}

enum SecondEnum {
    case First([FirstEnum])
}

struct EarlyInsideStruct {
    var y: Bool
}

struct LaterOutsideStruct {
    var x: EarlyInsideStruct
}

struct EarlyOutsideStruct {
    var x: LaterInsideStruct
}

struct LaterInsideStruct {
    var y: Bool
}

struct FirstStruct {
    var second: [SecondStruct]
}

struct SecondStruct {
    var first: [FirstStruct]
}

func rust_mem_leaked() -> UInt {
    return _ffi_fn_rust_mem_leaked()
}
