// This file was generated by miniffi v0.1.0. Do not edit.

#include "ffi.h"

extern "C" {

int32_t _ffi_fn_i32_to_big(int32_t big);
int32_t _ffi_fn_i32_to_foo(int32_t foo);
uintptr_t _ffi_fn_rust_mem_leaked();

} // extern "C"

rust::Big rust::i32_to_big(int32_t big) {
    auto ret_raw = _ffi_fn_i32_to_big(big);
    return rust::Big(ret_raw);
}

rust::Foo rust::i32_to_foo(int32_t foo) {
    auto ret_raw = _ffi_fn_i32_to_foo(foo);
    return rust::Foo(ret_raw);
}

uintptr_t rust::rust_mem_leaked() {
    return _ffi_fn_rust_mem_leaked();
}
