// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

namespace rust {

enum struct Big : int32_t {
    Min = -2147483647 - 1,
    Max = 2147483647,
};

enum struct Foo : int32_t {
    Zero = 0,
    One = 1,
    Hundred = 100,
};

uintptr_t rust_mem_leaked();

Foo i32_to_foo(int32_t foo);

Big i32_to_big(int32_t big);

} // namespace rust
