// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <memory>
#include <stdint.h>

namespace rust {

struct Adder {
    virtual ~Adder() {}
    virtual int32_t add(int32_t x) = 0;
};

uintptr_t rust_mem_leaked();

uint32_t get_counter();

std::shared_ptr<Adder> get_adder_rc(int32_t x);

std::unique_ptr<Adder> get_adder_box(int32_t x);

} // namespace rust
