// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export interface Tree {
    value: number,
    left: Tree | null,
    right: Tree | null,
}

export function rust_mem_leaked(): number;
export function sum_tree(tree: Tree): number;
export function check_nested(x: number): number;
