// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

uintptr_t _ffi_fn_rust_mem_leaked();

int32_t _ffi_fn_test_alignas(int32_t alignas2);

int32_t _ffi_fn_test_alignof(int32_t alignof2);

int32_t _ffi_fn_test_and(int32_t and2);

int32_t _ffi_fn_test_and_eq(int32_t and_eq2);

int32_t _ffi_fn_test_asm(int32_t asm2);

int32_t _ffi_fn_test_associatedtype(int32_t associatedtype2);

int32_t _ffi_fn_test_associativity(int32_t associativity2);

int32_t _ffi_fn_test_atomic_cancel(int32_t atomic_cancel2);

int32_t _ffi_fn_test_atomic_commit(int32_t atomic_commit2);

int32_t _ffi_fn_test_atomic_noexcept(int32_t atomic_noexcept2);

int32_t _ffi_fn_test_auto(int32_t auto2);

int32_t _ffi_fn_test_bitand(int32_t bitand2);

int32_t _ffi_fn_test_bitor(int32_t bitor2);

int32_t _ffi_fn_test_bool(int32_t bool2);

int32_t _ffi_fn_test_boolean(int32_t boolean);

int32_t _ffi_fn_test_borrowing(int32_t borrowing2);

int32_t _ffi_fn_test_byte(int32_t byte);

int32_t _ffi_fn_test_case(int32_t case2);

int32_t _ffi_fn_test_catch(int32_t catch2);

int32_t _ffi_fn_test_char(int32_t char2);

int32_t _ffi_fn_test_char16_t(int32_t char16_t2);

int32_t _ffi_fn_test_char32_t(int32_t char32_t2);

int32_t _ffi_fn_test_char8_t(int32_t char8_t2);

int32_t _ffi_fn_test_class(int32_t class2);

int32_t _ffi_fn_test_co_await(int32_t co_await2);

int32_t _ffi_fn_test_co_return(int32_t co_return2);

int32_t _ffi_fn_test_co_yield(int32_t co_yield2);

int32_t _ffi_fn_test_compl(int32_t compl2);

int32_t _ffi_fn_test_concept(int32_t concept2);

int32_t _ffi_fn_test_const_cast(int32_t const_cast2);

int32_t _ffi_fn_test_consteval(int32_t consteval2);

int32_t _ffi_fn_test_constexpr(int32_t constexpr2);

int32_t _ffi_fn_test_constinit(int32_t constinit2);

int32_t _ffi_fn_test_consuming(int32_t consuming2);

int32_t _ffi_fn_test_contract_assert(int32_t contract_assert2);

int32_t _ffi_fn_test_convenience(int32_t convenience2);

int32_t _ffi_fn_test_debugger(int32_t debugger);

int32_t _ffi_fn_test_decltype(int32_t decltype2);

int32_t _ffi_fn_test_default(int32_t default2);

int32_t _ffi_fn_test_defer(int32_t defer2);

int32_t _ffi_fn_test_deinit(int32_t deinit2);

int32_t _ffi_fn_test_delete(int32_t delete2);

int32_t _ffi_fn_test_double(int32_t double2);

int32_t _ffi_fn_test_dynamic(int32_t dynamic2);

int32_t _ffi_fn_test_dynamic_cast(int32_t dynamic_cast2);

int32_t _ffi_fn_test_explicit(int32_t explicit2);

int32_t _ffi_fn_test_export(int32_t export2);

int32_t _ffi_fn_test_extends(int32_t extends);

int32_t _ffi_fn_test_extension(int32_t extension2);

int32_t _ffi_fn_test_fallthrough(int32_t fallthrough2);

int32_t _ffi_fn_test_fileprivate(int32_t fileprivate2);

int32_t _ffi_fn_test_finally(int32_t finally);

int32_t _ffi_fn_test_float(int32_t float2);

int32_t _ffi_fn_test_friend(int32_t friend2);

int32_t _ffi_fn_test_func(int32_t func2);

int32_t _ffi_fn_test_function(int32_t function);

int32_t _ffi_fn_test_get(int32_t get2);

int32_t _ffi_fn_test_goto(int32_t goto2);

int32_t _ffi_fn_test_guard(int32_t guard2);

int32_t _ffi_fn_test_implements(int32_t implements);

int32_t _ffi_fn_test_import(int32_t import2);

int32_t _ffi_fn_test_indirect(int32_t indirect2);

int32_t _ffi_fn_test_infix(int32_t infix2);

int32_t _ffi_fn_test_init(int32_t init2);

int32_t _ffi_fn_test_inline(int32_t inline2);

int32_t _ffi_fn_test_inout(int32_t inout2);

int32_t _ffi_fn_test_instanceof(int32_t instanceof);

int32_t _ffi_fn_test_int(int32_t int2);

int32_t _ffi_fn_test_interface(int32_t interface);

int32_t _ffi_fn_test_internal(int32_t internal2);

int32_t _ffi_fn_test_is(int32_t is2);

int32_t _ffi_fn_test_lazy(int32_t lazy2);

int32_t _ffi_fn_test_left(int32_t left2);

int32_t _ffi_fn_test_long(int32_t long2);

int32_t _ffi_fn_test_mutable(int32_t mutable2);

int32_t _ffi_fn_test_mutating(int32_t mutating2);

int32_t _ffi_fn_test_namespace(int32_t namespace2);

int32_t _ffi_fn_test_native(int32_t native);

int32_t _ffi_fn_test_new(int32_t new2);

int32_t _ffi_fn_test_nil(int32_t nil2);

int32_t _ffi_fn_test_noexcept(int32_t noexcept2);

int32_t _ffi_fn_test_none(int32_t none2);

int32_t _ffi_fn_test_nonisolated(int32_t nonisolated2);

int32_t _ffi_fn_test_nonmutating(int32_t nonmutating2);

int32_t _ffi_fn_test_not(int32_t not2);

int32_t _ffi_fn_test_not_eq(int32_t not_eq2);

int32_t _ffi_fn_test_null(int32_t null);

int32_t _ffi_fn_test_nullptr(int32_t nullptr2);

int32_t _ffi_fn_test_open(int32_t open2);

int32_t _ffi_fn_test_operator(int32_t operator2);

int32_t _ffi_fn_test_optional(int32_t optional2);

int32_t _ffi_fn_test_or(int32_t or2);

int32_t _ffi_fn_test_or_eq(int32_t or_eq2);

int32_t _ffi_fn_test_package(int32_t package2);

int32_t _ffi_fn_test_postfix(int32_t postfix2);

int32_t _ffi_fn_test_precedence(int32_t precedence2);

int32_t _ffi_fn_test_precedencegroup(int32_t precedencegroup2);

int32_t _ffi_fn_test_prefix(int32_t prefix2);

int32_t _ffi_fn_test_private(int32_t private2);

int32_t _ffi_fn_test_protected(int32_t protected2);

int32_t _ffi_fn_test_protocol(int32_t protocol2);

int32_t _ffi_fn_test_public(int32_t public2);

int32_t _ffi_fn_test_reflexpr(int32_t reflexpr2);

int32_t _ffi_fn_test_register(int32_t register2);

int32_t _ffi_fn_test_reinterpret_cast(int32_t reinterpret_cast2);

int32_t _ffi_fn_test_repeat(int32_t repeat2);

int32_t _ffi_fn_test_required(int32_t required2);

int32_t _ffi_fn_test_requires(int32_t requires2);

int32_t _ffi_fn_test_rethrows(int32_t rethrows2);

int32_t _ffi_fn_test_right(int32_t right2);

int32_t _ffi_fn_test_set(int32_t set2);

int32_t _ffi_fn_test_short(int32_t short2);

int32_t _ffi_fn_test_signed(int32_t signed2);

int32_t _ffi_fn_test_sizeof(int32_t sizeof2);

int32_t _ffi_fn_test_some(int32_t some2);

int32_t _ffi_fn_test_static_assert(int32_t static_assert2);

int32_t _ffi_fn_test_static_cast(int32_t static_cast2);

int32_t _ffi_fn_test_subscript(int32_t subscript2);

int32_t _ffi_fn_test_switch(int32_t switch2);

int32_t _ffi_fn_test_synchronized(int32_t synchronized2);

int32_t _ffi_fn_test_template(int32_t template2);

int32_t _ffi_fn_test_this(int32_t this2);

int32_t _ffi_fn_test_thread_local(int32_t thread_local2);

int32_t _ffi_fn_test_throw(int32_t throw2);

int32_t _ffi_fn_test_throws(int32_t throws2);

int32_t _ffi_fn_test_transient(int32_t transient);

int32_t _ffi_fn_test_typealias(int32_t typealias2);

int32_t _ffi_fn_test_typedef(int32_t typedef2);

int32_t _ffi_fn_test_typeid(int32_t typeid2);

int32_t _ffi_fn_test_typename(int32_t typename2);

int32_t _ffi_fn_test_undefined(int32_t undefined);

int32_t _ffi_fn_test_union(int32_t union2);

int32_t _ffi_fn_test_unowned(int32_t unowned2);

int32_t _ffi_fn_test_unsigned(int32_t unsigned2);

int32_t _ffi_fn_test_using(int32_t using2);

int32_t _ffi_fn_test_var(int32_t var2);

int32_t _ffi_fn_test_void(int32_t void2);

int32_t _ffi_fn_test_volatile(int32_t volatile2);

int32_t _ffi_fn_test_wchar_t(int32_t wchar_t2);

int32_t _ffi_fn_test_weak(int32_t weak2);

int32_t _ffi_fn_test_with(int32_t with);

int32_t _ffi_fn_test_xor(int32_t xor2);

int32_t _ffi_fn_test_xor_eq(int32_t xor_eq2);

#ifdef __cplusplus
}
#endif
