// This file was generated by miniffi v0.1.0. Do not edit.

#[no_mangle]
extern "C" fn _ffi_fn_rust_mem_leaked() -> usize {
    rust_mem_leaked()
}

#[no_mangle]
extern "C" fn _ffi_fn_test_alignas(alignas: i32) -> i32 {
    test_alignas(alignas)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_alignof(alignof: i32) -> i32 {
    test_alignof(alignof)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_and(and: i32) -> i32 {
    test_and(and)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_and_eq(and_eq: i32) -> i32 {
    test_and_eq(and_eq)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_asm(asm: i32) -> i32 {
    test_asm(asm)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_associatedtype(associatedtype: i32) -> i32 {
    test_associatedtype(associatedtype)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_associativity(associativity: i32) -> i32 {
    test_associativity(associativity)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_atomic_cancel(atomic_cancel: i32) -> i32 {
    test_atomic_cancel(atomic_cancel)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_atomic_commit(atomic_commit: i32) -> i32 {
    test_atomic_commit(atomic_commit)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_atomic_noexcept(atomic_noexcept: i32) -> i32 {
    test_atomic_noexcept(atomic_noexcept)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_auto(auto: i32) -> i32 {
    test_auto(auto)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_bitand(bitand: i32) -> i32 {
    test_bitand(bitand)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_bitor(bitor: i32) -> i32 {
    test_bitor(bitor)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_bool(bool: i32) -> i32 {
    test_bool(bool)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_boolean(boolean2: i32) -> i32 {
    test_boolean(boolean2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_borrowing(borrowing: i32) -> i32 {
    test_borrowing(borrowing)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_byte(byte2: i32) -> i32 {
    test_byte(byte2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_case(case2: i32) -> i32 {
    test_case(case2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_catch(catch2: i32) -> i32 {
    test_catch(catch2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_char(char2: i32) -> i32 {
    test_char(char2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_char16_t(char16_t: i32) -> i32 {
    test_char16_t(char16_t)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_char32_t(char32_t: i32) -> i32 {
    test_char32_t(char32_t)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_char8_t(char8_t: i32) -> i32 {
    test_char8_t(char8_t)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_class(class2: i32) -> i32 {
    test_class(class2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_co_await(co_await: i32) -> i32 {
    test_co_await(co_await)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_co_return(co_return: i32) -> i32 {
    test_co_return(co_return)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_co_yield(co_yield: i32) -> i32 {
    test_co_yield(co_yield)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_compl(compl: i32) -> i32 {
    test_compl(compl)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_concept(concept: i32) -> i32 {
    test_concept(concept)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_const_cast(const_cast: i32) -> i32 {
    test_const_cast(const_cast)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_consteval(consteval: i32) -> i32 {
    test_consteval(consteval)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_constexpr(constexpr: i32) -> i32 {
    test_constexpr(constexpr)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_constinit(constinit: i32) -> i32 {
    test_constinit(constinit)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_consuming(consuming: i32) -> i32 {
    test_consuming(consuming)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_contract_assert(contract_assert: i32) -> i32 {
    test_contract_assert(contract_assert)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_convenience(convenience: i32) -> i32 {
    test_convenience(convenience)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_debugger(debugger2: i32) -> i32 {
    test_debugger(debugger2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_decltype(decltype: i32) -> i32 {
    test_decltype(decltype)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_default(default2: i32) -> i32 {
    test_default(default2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_defer(defer: i32) -> i32 {
    test_defer(defer)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_deinit(deinit: i32) -> i32 {
    test_deinit(deinit)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_delete(delete2: i32) -> i32 {
    test_delete(delete2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_double(double2: i32) -> i32 {
    test_double(double2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_dynamic(dynamic: i32) -> i32 {
    test_dynamic(dynamic)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_dynamic_cast(dynamic_cast: i32) -> i32 {
    test_dynamic_cast(dynamic_cast)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_explicit(explicit: i32) -> i32 {
    test_explicit(explicit)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_export(export2: i32) -> i32 {
    test_export(export2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_extends(extends2: i32) -> i32 {
    test_extends(extends2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_extension(extension: i32) -> i32 {
    test_extension(extension)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_fallthrough(fallthrough: i32) -> i32 {
    test_fallthrough(fallthrough)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_fileprivate(fileprivate: i32) -> i32 {
    test_fileprivate(fileprivate)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_finally(finally2: i32) -> i32 {
    test_finally(finally2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_float(float2: i32) -> i32 {
    test_float(float2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_friend(friend: i32) -> i32 {
    test_friend(friend)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_func(func: i32) -> i32 {
    test_func(func)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_function(function2: i32) -> i32 {
    test_function(function2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_get(get: i32) -> i32 {
    test_get(get)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_goto(goto2: i32) -> i32 {
    test_goto(goto2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_guard(guard: i32) -> i32 {
    test_guard(guard)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_implements(implements2: i32) -> i32 {
    test_implements(implements2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_import(import2: i32) -> i32 {
    test_import(import2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_indirect(indirect: i32) -> i32 {
    test_indirect(indirect)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_infix(infix: i32) -> i32 {
    test_infix(infix)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_init(init: i32) -> i32 {
    test_init(init)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_inline(inline: i32) -> i32 {
    test_inline(inline)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_inout(inout: i32) -> i32 {
    test_inout(inout)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_instanceof(instanceof2: i32) -> i32 {
    test_instanceof(instanceof2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_int(int2: i32) -> i32 {
    test_int(int2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_interface(interface2: i32) -> i32 {
    test_interface(interface2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_internal(internal: i32) -> i32 {
    test_internal(internal)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_is(is: i32) -> i32 {
    test_is(is)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_lazy(lazy: i32) -> i32 {
    test_lazy(lazy)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_left(left: i32) -> i32 {
    test_left(left)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_long(long2: i32) -> i32 {
    test_long(long2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_mutable(mutable: i32) -> i32 {
    test_mutable(mutable)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_mutating(mutating: i32) -> i32 {
    test_mutating(mutating)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_namespace(namespace: i32) -> i32 {
    test_namespace(namespace)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_native(native2: i32) -> i32 {
    test_native(native2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_new(new2: i32) -> i32 {
    test_new(new2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_nil(nil: i32) -> i32 {
    test_nil(nil)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_noexcept(noexcept: i32) -> i32 {
    test_noexcept(noexcept)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_none(none: i32) -> i32 {
    test_none(none)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_nonisolated(nonisolated: i32) -> i32 {
    test_nonisolated(nonisolated)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_nonmutating(nonmutating: i32) -> i32 {
    test_nonmutating(nonmutating)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_not(not: i32) -> i32 {
    test_not(not)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_not_eq(not_eq: i32) -> i32 {
    test_not_eq(not_eq)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_null(null2: i32) -> i32 {
    test_null(null2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_nullptr(nullptr: i32) -> i32 {
    test_nullptr(nullptr)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_open(open: i32) -> i32 {
    test_open(open)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_operator(operator: i32) -> i32 {
    test_operator(operator)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_optional(optional: i32) -> i32 {
    test_optional(optional)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_or(or: i32) -> i32 {
    test_or(or)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_or_eq(or_eq: i32) -> i32 {
    test_or_eq(or_eq)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_package(package2: i32) -> i32 {
    test_package(package2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_postfix(postfix: i32) -> i32 {
    test_postfix(postfix)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_precedence(precedence: i32) -> i32 {
    test_precedence(precedence)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_precedencegroup(precedencegroup: i32) -> i32 {
    test_precedencegroup(precedencegroup)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_prefix(prefix: i32) -> i32 {
    test_prefix(prefix)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_private(private2: i32) -> i32 {
    test_private(private2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_protected(protected2: i32) -> i32 {
    test_protected(protected2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_protocol(protocol: i32) -> i32 {
    test_protocol(protocol)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_public(public2: i32) -> i32 {
    test_public(public2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_reflexpr(reflexpr: i32) -> i32 {
    test_reflexpr(reflexpr)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_register(register: i32) -> i32 {
    test_register(register)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_reinterpret_cast(reinterpret_cast: i32) -> i32 {
    test_reinterpret_cast(reinterpret_cast)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_repeat(repeat: i32) -> i32 {
    test_repeat(repeat)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_required(required: i32) -> i32 {
    test_required(required)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_requires(requires: i32) -> i32 {
    test_requires(requires)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_rethrows(rethrows: i32) -> i32 {
    test_rethrows(rethrows)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_right(right: i32) -> i32 {
    test_right(right)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_set(set: i32) -> i32 {
    test_set(set)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_short(short2: i32) -> i32 {
    test_short(short2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_signed(signed: i32) -> i32 {
    test_signed(signed)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_sizeof(sizeof: i32) -> i32 {
    test_sizeof(sizeof)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_some(some: i32) -> i32 {
    test_some(some)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_static_assert(static_assert: i32) -> i32 {
    test_static_assert(static_assert)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_static_cast(static_cast: i32) -> i32 {
    test_static_cast(static_cast)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_subscript(subscript: i32) -> i32 {
    test_subscript(subscript)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_switch(switch2: i32) -> i32 {
    test_switch(switch2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_synchronized(synchronized2: i32) -> i32 {
    test_synchronized(synchronized2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_template(template: i32) -> i32 {
    test_template(template)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_this(this2: i32) -> i32 {
    test_this(this2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_thread_local(thread_local: i32) -> i32 {
    test_thread_local(thread_local)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_throw(throw2: i32) -> i32 {
    test_throw(throw2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_throws(throws2: i32) -> i32 {
    test_throws(throws2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_transient(transient2: i32) -> i32 {
    test_transient(transient2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_typealias(typealias: i32) -> i32 {
    test_typealias(typealias)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_typedef(typedef: i32) -> i32 {
    test_typedef(typedef)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_typeid(typeid: i32) -> i32 {
    test_typeid(typeid)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_typename(typename: i32) -> i32 {
    test_typename(typename)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_undefined(undefined2: i32) -> i32 {
    test_undefined(undefined2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_union(union: i32) -> i32 {
    test_union(union)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_unowned(unowned: i32) -> i32 {
    test_unowned(unowned)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_unsigned(unsigned: i32) -> i32 {
    test_unsigned(unsigned)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_using(using: i32) -> i32 {
    test_using(using)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_var(var2: i32) -> i32 {
    test_var(var2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_void(void2: i32) -> i32 {
    test_void(void2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_volatile(volatile2: i32) -> i32 {
    test_volatile(volatile2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_wchar_t(wchar_t: i32) -> i32 {
    test_wchar_t(wchar_t)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_weak(weak: i32) -> i32 {
    test_weak(weak)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_with(with2: i32) -> i32 {
    test_with(with2)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_xor(xor: i32) -> i32 {
    test_xor(xor)
}

#[no_mangle]
extern "C" fn _ffi_fn_test_xor_eq(xor_eq: i32) -> i32 {
    test_xor_eq(xor_eq)
}
