// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>
#include <memory>
#include <optional>

namespace rust {

struct Tree;

struct Nested {
    std::unique_ptr<std::unique_ptr<std::unique_ptr<int32_t>>> _0;
    bool operator == (const Nested&) const;
    bool operator != (const Nested& n) const { return !(*this == n); }
};

struct Tree {
    int32_t value = 0;
    std::optional<std::unique_ptr<Tree>> left;
    std::optional<std::unique_ptr<Tree>> right;
    bool operator == (const Tree&) const;
    bool operator != (const Tree& t) const { return !(*this == t); }
};

uintptr_t rust_mem_leaked();

Tree get_tree();

Nested check_nested(int32_t x);

} // namespace rust
