// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void* _ffi_alloc(intptr_t len);

int32_t _ffi_fn_check_nested(const void* buf_ptr);

uintptr_t _ffi_fn_rust_mem_leaked();

int32_t _ffi_fn_sum_tree(int32_t tree_value, const void* buf_ptr, _Bool has_tree_left, _Bool has_tree_right);

#ifdef __cplusplus
}
#endif
