// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void _ffi_Box_Handler__on_draw(const void*, const void* canvas_ptr);

void* _ffi_alloc(intptr_t len);

void _ffi_dealloc(const void* ptr, uintptr_t capacity);

void _ffi_fn_create_app(const void* platform_ptr);

uintptr_t _ffi_fn_rust_mem_leaked();

typedef struct {
    int32_t _0;
    int32_t _1;
} _ffi_ret_2_i32;

typedef struct {
    const void* _0;
    uintptr_t _1;
} _ffi_ret_ptr_usize;

void _ffi_rs_drop_Box_Handler(const void* ptr);

#ifdef __cplusplus
}
#endif
