// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void* _ffi_alloc(intptr_t len);

uintptr_t _ffi_fn_rust_mem_leaked();

_Bool _ffi_fn_set_tests(const void* buf_ptr, uintptr_t tests_len);

#ifdef __cplusplus
}
#endif
