// This file was generated by miniffi v0.1.0. Do not edit.

func rust_mem_leaked() -> UInt {
    return _ffi_fn_rust_mem_leaked()
}

func add_void(_ x: Int32, _ y: Int32) {
    _ffi_fn_add_void(x, y)
}

func add_empty_tuple(_ x: Int32, _ y: Int32) -> () {
    _ffi_fn_add_empty_tuple(x, y)
    return ()
}

func get_result() -> Int32 {
    return _ffi_fn_get_result()
}

func wild_arg(_ _1: Int32, _ _2: (), _ _3: Int32) -> () {
    _ffi_fn_wild_arg(_1, _3)
    return ()
}
