// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export interface FirstTrait {
    second(): SecondTrait;
}

export interface SecondTrait {
    first(): FirstTrait;
}

export type EarlyInsideEnum =
    | { readonly $: "Value", 0: boolean }

export type LaterOutsideEnum =
    | { readonly $: "Value", 0: EarlyInsideEnum }

export type EarlyOutsideEnum =
    | { readonly $: "Value", 0: LaterInsideEnum }

export type LaterInsideEnum =
    | { readonly $: "Value", 0: boolean }

export type FirstEnum =
    | { readonly $: "Second", 0: SecondEnum[] }

export type SecondEnum =
    | { readonly $: "First", 0: FirstEnum[] }

export interface EarlyInsideStruct {
    y: boolean,
}

export interface LaterOutsideStruct {
    x: EarlyInsideStruct,
}

export interface EarlyOutsideStruct {
    x: LaterInsideStruct,
}

export interface LaterInsideStruct {
    y: boolean,
}

export interface FirstStruct {
    second: SecondStruct[],
}

export interface SecondStruct {
    first: FirstStruct[],
}

export function rust_mem_leaked(): number;
