// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export function rust_mem_leaked(): number;
export function add_option(x: number | null, y: number | null): number;
export function add_nested(x: number | null, y: number | null): number;
export function add_all(x: (number | null)[]): number;
export function join_all(x: (string | null)[]): string;
