// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export function rust_mem_leaked(): number;
export function opt_int(x: boolean, y: number): number | null;
export function opt_opt_int(x: boolean, y: boolean, z: number): number | null;
export function vec_opt_int(n: number): (number | null)[];
export function opt_vec_opt_string(n: number): (string | null)[] | null;
