// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

uintptr_t _ffi_fn_rust_mem_leaked();

#ifdef __cplusplus
}
#endif
