// This file was generated by miniffi v0.1.0. Do not edit.

export async function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }> {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiate(bytes, { env });
    _ffi_exports = (await promise).instance.exports as any;
    return { memory: _ffi_exports.memory };
}

export async function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }> {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiateStreaming(source, { env });
    _ffi_exports = (await promise).instance.exports as any;
    return { memory: _ffi_exports.memory };
}

export function rust_mem_leaked(): number {
    return _ffi_exports._ffi_fn_rust_mem_leaked();
}

export function single_element_tuple(x: number): [number] {
    let ret_0 = _ffi_exports._ffi_fn_single_element_tuple(x);
    return [ret_0];
}

export function return_pair(x: number, y: boolean): [number, boolean] {
    let multi_ret = _ffi_exports._ffi_fn_return_pair(x, y);
    let ret_0 = _ffi_update_dv().getFloat32(multi_ret, true);
    let ret_1 = _ffi_dv.getUint8(multi_ret + 4);
    return [ret_0, !!ret_1];
}

let _ffi_dv: DataView;

function _ffi_update_dv(): DataView {
    let buffer = _ffi_exports.memory.buffer;
    if (!_ffi_dv || _ffi_dv.buffer !== buffer) _ffi_dv = new DataView(buffer);
    return _ffi_dv;
}

let _ffi_exports: {
    memory: WebAssembly.Memory,
    _ffi_fn_return_pair: (x: number, y: boolean) => number,
    _ffi_fn_rust_mem_leaked: () => number,
    _ffi_fn_single_element_tuple: (x: number) => number,
};

const _ffi_imports = {};
