// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export function rust_mem_leaked(): number;
export function add_void(x: number, y: number): void;
export function add_empty_tuple(x: number, y: number): undefined;
export function get_result(): number;
export function wild_arg(_1: number, _2: undefined, _3: number): undefined;
