// This file was generated by miniffi v0.1.0. Do not edit.

struct EmptyStruct {
}

struct SingleElementStruct {
    var _0: Int32
}

struct PairStruct {
    var x: Float32
    var y: Float32
}

func rust_mem_leaked() -> UInt {
    return _ffi_fn_rust_mem_leaked()
}

func empty_tuple(_ x: Int32, _ foo: EmptyStruct, _ y: Int32) -> Int32 {
    return _ffi_fn_empty_tuple(x, y)
}

func single_element_tuple(_ x: SingleElementStruct, _ y: SingleElementStruct) -> Int32 {
    return _ffi_fn_single_element_tuple(x._0, y._0)
}

func multiply_pairs(_ ab: PairStruct, _ cd: PairStruct) -> Float32 {
    return _ffi_fn_multiply_pairs(ab.x, ab.y, cd.x, cd.y)
}
