// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <optional>
#include <stdint.h>
#include <string>
#include <vector>

namespace rust {

uintptr_t rust_mem_leaked();

std::optional<int32_t> opt_int(bool x, int32_t y);

std::optional<std::optional<int32_t>> opt_opt_int(bool x, bool y, int32_t z);

std::vector<std::optional<int32_t>> vec_opt_int(int32_t n);

std::optional<std::vector<std::optional<std::string>>> opt_vec_opt_string(int32_t n);

} // namespace rust
