// This file was generated by miniffi v0.1.0. Do not edit.

#include "ffi.h"

extern "C" {

int32_t _ffi_fn_big_to_i32(int32_t big_raw);
int32_t _ffi_fn_foo_to_i32(int32_t foo_raw);
uintptr_t _ffi_fn_rust_mem_leaked();

} // extern "C"

int32_t rust::big_to_i32(rust::Big big) {
    return _ffi_fn_big_to_i32(int32_t(big));
}

int32_t rust::foo_to_i32(rust::Foo foo) {
    return _ffi_fn_foo_to_i32(int32_t(foo));
}

uintptr_t rust::rust_mem_leaked() {
    return _ffi_fn_rust_mem_leaked();
}
