// This file was generated by miniffi v0.1.0. Do not edit.

#include "ffi.h"
#include <stdlib.h>
#include <vector>

extern "C" {

int32_t _ffi_fn_big_to_i32(int32_t big_raw);
int32_t _ffi_fn_foo_to_i32(int32_t foo_raw);
void _ffi_fn_long_in(const void* buf_ptr);
void* _ffi_alloc(uintptr_t len);
uintptr_t _ffi_fn_rust_mem_leaked();

} // extern "C"

namespace {

template <typename T>
void _ffi_write(T val, std::vector<uint8_t> &buf) {
    buf.insert(buf.end(), (const uint8_t*)&val, (const uint8_t*)&val + sizeof(T));
}

void _ffi_enum_LongEnum_to_rust(rust::LongEnum val, std::vector<uint8_t>& buf) {
    if (val.is<rust::LongEnum::Empty>()) {
        _ffi_write(int32_t(0), buf);
    } else if (auto it = val.as<rust::LongEnum::ShortTuple>()) {
        _ffi_write(int32_t(1), buf);
        _ffi_write(it->_0, buf);
    } else if (auto it = val.as<rust::LongEnum::ShortStruct>()) {
        _ffi_write(int32_t(2), buf);
        _ffi_write(it->a, buf);
    } else if (auto it = val.as<rust::LongEnum::LongTuple>()) {
        _ffi_write(int32_t(3), buf);
        _ffi_write(it->_0, buf);
        _ffi_write(it->_1, buf);
        _ffi_write(it->_2, buf);
        _ffi_write(it->_3, buf);
        _ffi_write(it->_4, buf);
        _ffi_write(it->_5, buf);
        _ffi_write(it->_6, buf);
        _ffi_write(it->_7, buf);
    } else if (auto it = val.as<rust::LongEnum::LongStruct>()) {
        _ffi_write(int32_t(4), buf);
        _ffi_write(it->a, buf);
        _ffi_write(it->b, buf);
        _ffi_write(it->c, buf);
        _ffi_write(it->d, buf);
        _ffi_write(it->e, buf);
        _ffi_write(it->f, buf);
    } else {
        abort();
    }
}

const void* _ffi_vec_to_rust(const std::vector<uint8_t>& vec) {
    return memcpy(_ffi_alloc(vec.size()), vec.data(), vec.size());
}

} // namespace

int32_t rust::big_to_i32(rust::Big big) {
    return _ffi_fn_big_to_i32(int32_t(big));
}

int32_t rust::foo_to_i32(rust::Foo foo) {
    return _ffi_fn_foo_to_i32(int32_t(foo));
}

void rust::long_in(rust::LongEnum _1) {
    std::vector<uint8_t> buf;
    _ffi_enum_LongEnum_to_rust(std::move(_1), buf);
    auto buf_ptr = _ffi_vec_to_rust(buf);
    _ffi_fn_long_in(buf_ptr);
}

uintptr_t rust::rust_mem_leaked() {
    return _ffi_fn_rust_mem_leaked();
}
