// This file was generated by miniffi v0.1.0. Do not edit.

export async function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }> {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiate(bytes, { env });
    _ffi_exports = (await promise).instance.exports as any;
    return { memory: _ffi_exports.memory };
}

export async function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }> {
    let env = Object.assign({}, imports, _ffi_imports);
    let promise = WebAssembly.instantiateStreaming(source, { env });
    _ffi_exports = (await promise).instance.exports as any;
    return { memory: _ffi_exports.memory };
}

export const CONST_FALSE: boolean = false;
export const CONST_TRUE: boolean = true;
export const CONST_U8_MIN: number = 0;
export const CONST_U8_MAX: number = 255;
export const CONST_U16_MIN: number = 0;
export const CONST_U16_MAX: number = 65535;
export const CONST_U32_MIN: number = 0;
export const CONST_U32_MAX: number = 4294967295;
export const CONST_U64_MIN: bigint = 0n;
export const CONST_U64_MAX: bigint = 18446744073709551615n;
export const CONST_I8_MIN: number = -128;
export const CONST_I8_MAX: number = 127;
export const CONST_I16_MIN: number = -32768;
export const CONST_I16_MAX: number = 32767;
export const CONST_I32_MIN: number = -2147483648;
export const CONST_I32_MAX: number = 2147483647;
export const CONST_I64_MIN: bigint = -9223372036854775808n;
export const CONST_I64_MAX: bigint = 9223372036854775807n;
export const CONST_F32_NEG_0: number = -0;
export const CONST_F64_NEG_0: number = -0;
export const CONST_F32_PI: number = 3.1415927410125732;
export const CONST_F64_PI: number = -3.141592653589793;
export const CONST_STRING: string = "\x00\r\n🦀";

export function rust_mem_leaked(): number {
    return _ffi_exports._ffi_fn_rust_mem_leaked();
}

let _ffi_exports: {
    memory: WebAssembly.Memory,
    _ffi_fn_rust_mem_leaked: () => number,
};

const _ffi_imports = {};
