// This file was generated by miniffi v0.1.0. Do not edit.

#[no_mangle]
extern "C" fn _ffi_fn_empty_tuple(x: i32, y: i32) -> i32 {
    empty_tuple(x, EmptyStruct, y)
}

#[no_mangle]
extern "C" fn _ffi_fn_multiply_pairs(ab_x: f32, ab_y: f32, cd_x: f32, cd_y: f32) -> f32 {
    multiply_pairs(PairStruct { x: ab_x, y: ab_y }, PairStruct { x: cd_x, y: cd_y })
}

#[no_mangle]
extern "C" fn _ffi_fn_rust_mem_leaked() -> usize {
    rust_mem_leaked()
}

#[no_mangle]
extern "C" fn _ffi_fn_single_element_tuple(x_0: i32, y_0: i32) -> i32 {
    single_element_tuple(SingleElementStruct(x_0), SingleElementStruct(y_0))
}
