// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export type Foo =
    | { readonly $: "Empty" }
    | { readonly $: "Single", 0: number }
    | { readonly $: "Point", x: number, y: number }
    | { readonly $: "Nested", 0: Foo }

export function rust_mem_leaked(): number;
export function set_tests(tests: Foo[]): boolean;
