// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>
#include <string>

namespace rust {

uintptr_t rust_mem_leaked();

void reset();

int32_t get_string_len();

std::string get_string();

void set_string(std::string x);

void set_str(std::string x);

} // namespace rust
