// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void* _ffi_alloc(intptr_t len);

uintptr_t _ffi_fn_rust_mem_leaked();

int32_t _ffi_fn_test(int32_t x_0, const void* x_1_ptr_ptr, const void* buf_ptr, uintptr_t x_2_len);

#ifdef __cplusplus
}
#endif
