// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t _ffi_Box_Adder__add(const void*, int32_t x);

int32_t _ffi_Rc_Adder__add(const void*, int32_t x);

const void* _ffi_fn_get_adder_box(int32_t x);

const void* _ffi_fn_get_adder_rc(int32_t x);

uint32_t _ffi_fn_get_counter();

uintptr_t _ffi_fn_rust_mem_leaked();

void _ffi_rs_drop_Box_Adder(const void* ptr);

void _ffi_rs_drop_Rc_Adder(const void* ptr);

#ifdef __cplusplus
}
#endif
