// This file was generated by miniffi v0.1.0. Do not edit.

protocol Getter: AnyObject {
    func get_adder() -> Adder
}

protocol Adder: AnyObject {
    func add(_ x: Int32, _ y: Int32) -> Int32
}

func rust_mem_leaked() -> UInt {
    return _ffi_fn_rust_mem_leaked()
}

func get_getter_counter() -> UInt32 {
    return _ffi_fn_get_getter_counter()
}

func get_adder_counter() -> UInt32 {
    return _ffi_fn_get_adder_counter()
}

func get_getter() -> Getter {
    let ret_ptr = _ffi_fn_get_getter()
    return _ffi_Rc_Getter(ret_ptr)
}

private class _ffi_Rc_Adder : Adder {
    private var _ffi: UnsafeRawPointer?

    init(_ ptr: UnsafeRawPointer?) {
        _ffi = ptr
    }

    deinit {
        _ffi_rs_drop_Rc_Adder(_ffi)
    }

    func add(_ x: Int32, _ y: Int32) -> Int32 {
        return _ffi_Rc_Adder__add(_ffi, x, y)
    }
}

private class _ffi_Rc_Getter : Getter {
    private var _ffi: UnsafeRawPointer?

    init(_ ptr: UnsafeRawPointer?) {
        _ffi = ptr
    }

    deinit {
        _ffi_rs_drop_Rc_Getter(_ffi)
    }

    func get_adder() -> Adder {
        let ret_ptr = _ffi_Rc_Getter__get_adder(_ffi)
        return _ffi_Rc_Adder(ret_ptr)
    }
}
