// This file was generated by miniffi v0.1.0. Do not edit.

#[no_mangle]
extern "C" fn _ffi_fn_rust_mem_leaked() -> usize {
    rust_mem_leaked()
}

#[no_mangle]
extern "C" fn _ffi_fn_set_empty_tuple(tuple_in_ptr: *const u8) -> i32 {
    set_empty_tuple(std::rc::Rc::new(_ffi_rs_Rc_TupleIn(tuple_in_ptr)))
}

#[no_mangle]
extern "C" fn _ffi_fn_set_multiply_pairs(tuple_in_ptr: *const u8) -> f32 {
    set_multiply_pairs(std::rc::Rc::new(_ffi_rs_Rc_TupleIn(tuple_in_ptr)))
}

#[no_mangle]
extern "C" fn _ffi_fn_set_single_element_tuple(tuple_in_ptr: *const u8) -> i32 {
    set_single_element_tuple(std::rc::Rc::new(_ffi_rs_Rc_TupleIn(tuple_in_ptr)))
}

#[allow(non_camel_case_types)]
struct _ffi_rs_Rc_TupleIn(*const u8);

impl Drop for _ffi_rs_Rc_TupleIn {
    fn drop(&mut self) {
        extern "C" { fn _ffi_cpp_drop_Rc_TupleIn(_: *const u8); }
        unsafe { _ffi_cpp_drop_Rc_TupleIn(self.0) };
    }
}

impl TupleIn for _ffi_rs_Rc_TupleIn {
    fn empty_tuple(&self, x: i32, foo: (), y: i32) -> i32 {
        extern "C" { fn _ffi_cpp_Rc_TupleIn__empty_tuple(_: *const u8, x: i32, y: i32) -> i32; }
        _ = foo;
        unsafe { _ffi_cpp_Rc_TupleIn__empty_tuple(self.0, x, y) }
    }

    fn single_element_tuple(&self, x: (i32,), y: (i32,)) -> i32 {
        extern "C" { fn _ffi_cpp_Rc_TupleIn__single_element_tuple(_: *const u8, x_0: i32, y_0: i32) -> i32; }
        unsafe { _ffi_cpp_Rc_TupleIn__single_element_tuple(self.0, x.0, y.0) }
    }

    fn multiply_pairs(&self, ab: (f32, f32), cd: (f32, f32)) -> f32 {
        extern "C" { fn _ffi_cpp_Rc_TupleIn__multiply_pairs(_: *const u8, ab_0: f32, ab_1: f32, cd_0: f32, cd_1: f32) -> f32; }
        unsafe { _ffi_cpp_Rc_TupleIn__multiply_pairs(self.0, ab.0, ab.1, cd.0, cd.1) }
    }
}
