// This file was generated by miniffi v0.1.0. Do not edit.

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t _ffi_fn_empty_tuple(int32_t x, int32_t y);

float _ffi_fn_multiply_pairs(float ab_0, float ab_1, float cd_0, float cd_1);

int32_t _ffi_fn_nesting(int32_t x_0, int32_t x_2_0, int32_t x_2_1_0);

uintptr_t _ffi_fn_rust_mem_leaked();

int32_t _ffi_fn_single_element_tuple(int32_t x_0, int32_t y_0);

#ifdef __cplusplus
}
#endif
