// This file was generated by miniffi v0.1.0. Do not edit.

export function instantiate(bytes: BufferSource, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;
export function instantiateStreaming(source: Response | PromiseLike<Response>, imports?: WebAssembly.ModuleImports): Promise<{ memory: WebAssembly.Memory }>;

export interface Imported {
    add(x: number, y: number): number;
}

export interface Exported {
    run(imported: Imported): number;
}

export function rust_mem_leaked(): number;
export function get_exported(): Exported;
export function get_counter(): number;
