// This file was generated by miniffi v0.1.0. Do not edit.

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_add_empty_tuple(x: i32, y: i32) {
    _ = add_empty_tuple(x, y);
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_add_void(x: i32, y: i32) {
    add_void(x, y);
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_get_result() -> i32 {
    get_result()
}

#[unsafe(no_mangle)]
extern "C" fn _ffi_fn_rust_mem_leaked() -> usize {
    rust_mem_leaked()
}
